### ISSUE TITLE
Front#5 Place publique

### ISSUE THREAD

**Issue by l-hay-ling** [Coorjet/boko_app#45]

**Comment by Coorjet** [comment]
Il fadura ajouter un genre de bandeau  + fleche a droite de menu 1 et gauche du menu 2 pour éviter de toucher les boutons

**Comment by l-hay-ling** [comment]
Tu me reexpliqueras ça

**Comment by l-hay-ling** [comment]
viewflipper

**Comment by l-hay-ling** [comment]
Menu grosso merdo fini, je laisse les bouttons et ne fait pas de layout clickable pour le moment pour eviter les conflits lors du prochain merge

Peut rajouter un menu pop-up pour prévenir au slide avec un message "ne plus afficher ce pop-up"
