### ISSUE TITLE
Evolution#SaveUserData

### ISSUE THREAD

**Issue by Coorjet** [Coorjet/boko_app#7]
- Créer un Bean User ( comme Book)  type SugarORM
- Lors de l'édition du profil, si l'user n'existe pas : créer un User, et ajouter les éléments au Bean + Save,
   sinon, modifier l'user existant ( il ne doit exister qu'un seul User en local )
- Le profil doit charger les données de l'user existant à l'affichage.

**Comment by l-hay-ling** [comment]
- L'user doit également pouvoir changer d'images de profil
- Les informations de bases doivent être mit à l'inscription de l'utilisateur (à faire plus tard) pour l'instant on utilise des informations placebo
